pub mod gof;
pub mod optim;

pub use modelparams_derive::{ModelParams, Layers};

use rayon::prelude::*;

/// Map `f` over `items`, optionally in parallel.
/// Thread-safe for read-only closures.
pub fn par_map<A, B, F>(items: &[A], parallel: bool, f: F) -> Vec<B>
where
    F: Fn(&A) -> B + Sync + Send,
    A: Sync,
    B: Send,
{
    if parallel {
        items.par_iter().map(f).collect()
    } else {
        items.iter().map(f).collect()
    }
}

/// Map `f(item, state_clone)` over `items`, cloning `state` per item.
/// The original `state` is never modified; safe for both serial and parallel.
pub fn par_map_cloned<A, B, S, F>(items: &[A], state: &S, parallel: bool, f: F) -> Vec<B>
where
    F: Fn(&A, S) -> B + Sync + Send,
    A: Sync,
    S: Clone + Send + Sync,
    B: Send,
{
    if parallel {
        items.par_iter().map(|x| f(x, state.clone())).collect()
    } else {
        items.iter().map(|x| f(x, state.clone())).collect()
    }
}

// ── scalar parameter metadata ─────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct ParamInfo {
    pub name:    &'static str,
    pub bounds:  Option<(f64, f64)>,
    pub units:   &'static str,
    pub default: f64,
}

/// Trait for scalar (single-layer) parameter structs.
/// Generated by `#[derive(ModelParams)]`.
pub trait ModelParams {
    fn param_info() -> Vec<ParamInfo> where Self: Sized;
    fn get_values(&self) -> Vec<f64>;
    fn set_value(&mut self, index: usize, value: f64);

    fn opt_bounds(&self) -> (Vec<f64>, Vec<f64>, Vec<f64>) where Self: Sized {
        let info = Self::param_info();
        let vals = self.get_values();
        let mut x0 = vec![];  let mut lb = vec![];  let mut ub = vec![];
        for (p, &v) in info.iter().zip(vals.iter()).filter(|(p,_)| p.bounds.is_some()) {
            let (lo, hi) = p.bounds.unwrap();
            x0.push(v); lb.push(lo); ub.push(hi);
        }
        (x0, lb, ub)
    }

    fn update_from_opt(&mut self, values: &[f64]) where Self: Sized {
        let bounded: Vec<usize> = Self::param_info().iter().enumerate()
            .filter(|(_, p)| p.bounds.is_some()).map(|(i,_)| i).collect();
        for (opt_i, &struct_i) in bounded.iter().enumerate() {
            self.set_value(struct_i, values[opt_i]);
        }
    }

    fn print_params(&self) where Self: Sized {
        for (p, v) in Self::param_info().iter().zip(self.get_values().iter()) {
            match p.bounds {
                Some((lo, hi)) =>
                    println!("  {:<14} = {:>10.4}  [{:<12}]  bounds = ({:.3}, {:.3})",
                             p.name, v, p.units, lo, hi),
                None =>
                    println!("  {:<14} = {:>10.4}  [{:<12}]  bounds = none",
                             p.name, v, p.units),
            }
        }
    }
}

// ── nested / layered parameter system ────────────────────────────────────────

/// A parameter entry with its full hierarchical path.
/// path: e.g. `["hydraulic", "theta_sat", "2"]`
#[derive(Debug, Clone)]
pub struct PathParam {
    pub path:   Vec<String>,
    pub name:   String,
    pub value:  f64,
    pub bounds: Option<(f64, f64)>,
    pub units:  &'static str,
}

/// Trait for composite / layered models.
/// Generated by `#[derive(Layers)]` for layer structs.
/// Implement manually for composite models (e.g. `SoilModel`).
pub trait NestedModelParams {
    fn collect_params(&self, prefix: &[String]) -> Vec<PathParam>;
    fn update_param(&mut self, path: &[String], value: f64) -> bool;

    /// Convenience: collect with empty prefix.
    fn parameters(&self) -> Vec<PathParam> {
        self.collect_params(&[])
    }

    fn print_nested(&self) {
        for p in self.parameters() {
            let path = p.path.join(".");
            match p.bounds {
                Some((lo, hi)) =>
                    println!("  {:<30} = {:>10.4}  [{:<12}]  ({:.3}, {:.3})",
                             path, p.value, p.units, lo, hi),
                None =>
                    println!("  {:<30} = {:>10.4}  [{:<12}]  none",
                             path, p.value, p.units),
            }
        }
    }

    /// Extract (x0, lb, ub, paths) for optimisation.
    fn opt_bounds_nested(&self) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<Vec<String>>) {
        let mut x0 = vec![]; let mut lb = vec![]; let mut ub = vec![]; let mut paths = vec![];
        for p in self.parameters().into_iter().filter(|p| p.bounds.is_some()) {
            let (lo, hi) = p.bounds.unwrap();
            x0.push(p.value); lb.push(lo); ub.push(hi); paths.push(p.path);
        }
        (x0, lb, ub, paths)
    }

    fn update_from_paths(&mut self, paths: &[Vec<String>], values: &[f64]) {
        for (path, &value) in paths.iter().zip(values.iter()) {
            if !self.update_param(path, value) {
                eprintln!("warn: could not update path {:?}", path);
            }
        }
    }
}
